### ISSUE TITLE
OSError: could not find or load spatialindex_c-64.dll

### ISSUE THREAD

**Issue by orlandoandradeb** [geopandas/geopandas#1812]
Hello 

I have been using geopandas   without problems for a while. Now at the moment that I want to  import it   continually appear a error. I have installed the dependencies mentioned in the documentation. However, it gives me the following error:

"OSError: could not find or load spatialindex_c-64.dll"

I have no idea why it is and in several environments it gives me the same error

**Comment by martinfleis** [comment]
You have an issue with an installation of `rtree` and its dependencies. How did you install geopandas and its dependencies? pip, conda, wheels? You will have reinstall rtree to make sure it picks the underlying C library. Alternatively, you can try [installing pygeos](https://geopandas.readthedocs.io/en/latest/getting_started/install.html#using-the-optional-pygeos-dependency) in which case rtree is not used.

**Comment by orlandoandradeb** [comment]
Hello @martinfleis 
thank you! Unistalling rtree worked for me !

**Comment by martinfleis** [comment]
I am quite sure pyproj does not require rtree. Again, how did you install geopandas and its dependencies? pip, conda, wheels?

If you are using conda, can you show the output of `conda list`?

**Comment by orlandoandradeb** [comment]
(ambiente_quetzal) C:\Users\Hola\Documents\UPC\PhD\Papers\Paper 4\Modelo de demanda Guadalajara>conda list
# packages in environment at C:\Users\Hola\anaconda3\envs\ambiente_quetzal:
#
# Name                    Version                   Build  Channel
_r-mutex                  1.0.1               anacondar_1    conda-forge
aenum                     3.0.0                    pypi_0    pypi
affine                    2.3.0                      py_0    conda-forge
aiohttp                   3.7.3            py37hcc03f2d_1    conda-forge
alabaster                 0.7.12                   pypi_0    pypi
aniso8601                 8.1.1                    pypi_0    pypi
apply_defaults            0.1.4                      py_0    conda-forge
argcomplete               1.12.2                   pypi_0    pypi
argon2-cffi               20.1.0           py37hcc03f2d_2    conda-forge
astropy                   4.2                      pypi_0    pypi
async-timeout             3.0.1                   py_1000    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     20.3.0             pyhd3deb0d_0    conda-forge
babel                     2.9.0                    pypi_0    pypi
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports-abc             0.5                      pypi_0    pypi
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
beautifulsoup4            4.9.3                    pypi_0    pypi
bitarray                  1.6.3            py37h2bbff1b_1
bleach                    3.3.0              pyh44b312d_0    conda-forge
blosc                     1.21.0               h0e60522_0    conda-forge
boost-cpp                 1.74.0               h54f0996_2    conda-forge
branca                    0.4.2                    pypi_0    pypi
brotlipy                  0.7.0           py37hcc03f2d_1001    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2020.12.5            h5b45459_0    conda-forge
cairo                     1.16.0            hba8bd2f_1007    conda-forge
certifi                   2020.12.5                pypi_0    pypi
certipy                   0.1.3                      py_0    conda-forge
cffi                      1.14.4           py37hd8e9650_1    conda-forge
cfitsio                   3.470                h0af3d06_7    conda-forge
chardet                   3.0.4           py37hf50a25e_1008    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.1              pyhd8ed1ab_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
contextily                1.0.1                      py_0    conda-forge
cryptography              3.3.1            py37hd8e9650_1    conda-forge
curl                      7.71.1               h4b64cdc_8    conda-forge
cycler                    0.10.0                     py_2    conda-forge
datetime                  4.3                      pypi_0    pypi
dbf                       0.99.0                   pypi_0    pypi
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
descartes                 1.1.0                    pypi_0    pypi
docutils                  0.16                     pypi_0    pypi
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
et-xmlfile                1.0.1                    pypi_0    pypi
expat                     2.2.10               h39d44d4_0    conda-forge
fiona                     1.8.18           py37hc779931_0    conda-forge
folium                    0.12.1                   pypi_0    pypi
fontconfig                2.13.1            h1989441_1004    conda-forge
freetype                  2.10.4               h546665d_1    conda-forge
freexl                    1.0.5             hd288d7e_1002    conda-forge
gdal                      3.1.4                    pypi_0    pypi
geographiclib             1.50                       py_0    conda-forge
geojson                   2.5.0                    pypi_0    pypi
geopandas                 0.8.2              pyhd8ed1ab_0    conda-forge
geopy                     2.1.0              pyhd3deb0d_0    conda-forge
geos                      3.8.1                he025d50_0    conda-forge
geotiff                   1.6.0                h8884d1a_3    conda-forge
gettext                   0.19.8.1          h1a89ca6_1005    conda-forge
gf-kernel                 1.0.0              pyhd8ed1ab_0    conda-forge
gtfs-kit                  5.0.2                    pypi_0    pypi
hdf4                      4.2.13            h0e5069d_1004    conda-forge
hdf5                      1.10.6          nompi_h5268f04_1114    conda-forge
icu                       68.1                 h0e60522_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
imagesize                 1.2.0                    pypi_0    pypi
importlib-metadata        3.4.0            py37h03978a9_0    conda-forge
importlib_metadata        3.4.0                hd8ed1ab_0    conda-forge
intel-openmp              2020.3             h57928b3_311    conda-forge
ipykernel                 5.3.4            py37h5ca1d4c_0
ipython                   7.19.0           py37heaed05f_2    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.6.3              pyhd3deb0d_0    conda-forge
jdcal                     1.4.1                    pypi_0    pypi
jedi                      0.17.2           py37h03978a9_1    conda-forge
jinja2                    2.11.3             pyh44b312d_0    conda-forge
joblib                    1.0.0              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h8ffe710_0    conda-forge
json2html                 1.3.0                    pypi_0    pypi
jsonrpcserver             4.2.0              pyhd8ed1ab_0    conda-forge
jsonschema                3.2.0                      py_2    conda-forge
jupyter                   1.0.0            py37h03978a9_6    conda-forge
jupyter-server-proxy      1.5.3              pyhd8ed1ab_0    conda-forge
jupyter_client            6.1.11             pyhd8ed1ab_1    conda-forge
jupyter_console           6.2.0                      py_0    conda-forge
jupyter_core              4.7.1            py37h03978a9_0    conda-forge
jupyter_kernel_gateway    2.4.3              pyh9f0ad1d_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_widgets        1.0.0              pyhd8ed1ab_1    conda-forge
kealib                    1.4.14               ha3510f1_0    conda-forge
kiwisolver                1.3.1            py37h8c56517_1    conda-forge
kml2geojson               4.0.2                    pypi_0    pypi
krb5                      1.17.2               hbae68bd_0    conda-forge
libblas                   3.9.0                     7_mkl    conda-forge
libcblas                  3.9.0                     7_mkl    conda-forge
libclang                  11.0.1          default_h5c34c98_1    conda-forge
libcurl                   7.71.1               h4b64cdc_8    conda-forge
libffi                    3.3                  h0e60522_2    conda-forge
libgdal                   3.1.4                h3b415b5_2    conda-forge
libglib                   2.66.4               h48f9de8_2    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
libkml                    1.3.0             he9e54da_1012    conda-forge
liblapack                 3.9.0                     7_mkl    conda-forge
libnetcdf                 4.7.4           nompi_h3a9aa94_107    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libpq                     12.3                 h4f54205_3    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libspatialindex           1.9.3                he025d50_3    conda-forge
libspatialite             5.0.0                h37d8b57_0    conda-forge
libssh2                   1.9.0                hb06d900_5    conda-forge
libtiff                   4.2.0                hc10be44_0    conda-forge
libwebp-base              1.2.0                h8ffe710_0    conda-forge
libxml2                   2.9.10               hf5bbc77_3    conda-forge
lz4-c                     1.9.3                h8ffe710_0    conda-forge
m2w64-bwidget             1.9.10                        2    conda-forge
m2w64-bzip2               1.0.6                         6    conda-forge
m2w64-expat               2.1.1                         2    conda-forge
m2w64-fftw                3.3.4                         6    conda-forge
m2w64-flac                1.3.1                         3    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gettext             0.19.7                        2    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-gsl                 2.1                           2    conda-forge
m2w64-libiconv            1.14                          6    conda-forge
m2w64-libjpeg-turbo       1.4.2                         3    conda-forge
m2w64-libogg              1.3.2                         3    conda-forge
m2w64-libpng              1.6.21                        2    conda-forge
m2w64-libsndfile          1.0.26                        2    conda-forge
m2w64-libtiff             4.0.6                         2    conda-forge
m2w64-libvorbis           1.3.5                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
m2w64-libxml2             2.9.3                         3    conda-forge
m2w64-mpfr                3.1.4                         4    conda-forge
m2w64-pcre                8.38                          2    conda-forge
m2w64-speex               1.2rc2                        3    conda-forge
m2w64-speexdsp            1.2rc3                        3    conda-forge
m2w64-tcl                 8.6.5                         3    conda-forge
m2w64-tk                  8.6.5                         3    conda-forge
m2w64-tktable             2.10                          5    conda-forge
m2w64-wineditline         2.101                         5    conda-forge
m2w64-xz                  5.2.2                         2    conda-forge
m2w64-zlib                1.2.8                        10    conda-forge
markupsafe                1.1.1            py37hcc03f2d_3    conda-forge
matplotlib-base           3.3.4            py37h3379fd5_0    conda-forge
mercantile                1.1.6              pyh9f0ad1d_0    conda-forge
mistune                   0.8.4           py37hcc03f2d_1003    conda-forge
mkl                       2020.4             hb70f87d_311    conda-forge
mock                      4.0.3            py37h03978a9_1    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
multidict                 5.1.0            py37hcc03f2d_1    conda-forge
munch                     2.5.0                      py_0    conda-forge
nbclient                  0.5.1                      py_0    conda-forge
nbconvert                 6.0.7            py37h03978a9_3    conda-forge
nbformat                  5.1.2              pyhd8ed1ab_1    conda-forge
nest-asyncio              1.5.1                    pypi_0    pypi
networkx                  2.5                      pypi_0    pypi
notebook                  6.2.0            py37h03978a9_0    conda-forge
numexpr                   2.7.2            py37h08fd248_0    conda-forge
numpy                     1.20.0           py37hd20adf4_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.4.0                h48faf41_0    conda-forge
openpyxl                  3.0.6                    pypi_0    pypi
openssl                   1.1.1i               h8ffe710_0    conda-forge
osmnx                     0.11.4                   pypi_0    pypi
packaging                 20.9                     pypi_0    pypi
pandas                    1.2.1            py37h08fd248_0    conda-forge
pandoc                    2.11.4               h8ffe710_0    conda-forge
pandocfilters             1.4.3                    pypi_0    pypi
parso                     0.7.1              pyh9f0ad1d_0    conda-forge
pcre                      8.44                 ha925a31_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.1.0            py37hdec93a9_1    conda-forge
pip                       21.0.1             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h8ffe710_0    conda-forge
poppler                   0.89.0               h3772339_5    conda-forge
poppler-data              0.4.10                        0    conda-forge
postgresql                12.3                 h0f1a9bc_3    conda-forge
proj                      7.1.1                h7d85306_3    conda-forge
prometheus_client         0.9.0              pyhd3deb0d_0    conda-forge
prompt-toolkit            3.0.14             pyha770c72_0    conda-forge
prompt_toolkit            3.0.14               hd8ed1ab_0    conda-forge
pycountry                 19.8.18                  pypi_0    pypi
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyerfa                    1.7.1.1                  pypi_0    pypi
pygments                  2.7.4              pyhd8ed1ab_0    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pypdf                     1.13                     pypi_0    pypi
pyproj                    3.0.0.post1              pypi_0    pypi
pyqt                      5.12.3           py37h03978a9_7    conda-forge
pyqt-impl                 5.12.3           py37hf2a7229_7    conda-forge
pyqt5-sip                 4.19.18          py37hf2a7229_7    conda-forge
pyqtchart                 5.12             py37hf2a7229_7    conda-forge
pyqtwebengine             5.12.1           py37hf2a7229_7    conda-forge
pyrsistent                0.17.3           py37hcc03f2d_2    conda-forge
pysocks                   1.7.1            py37h03978a9_3    conda-forge
pytables                  3.6.1            py37hdc91d43_3    conda-forge
python                    3.7.9                h60c2a47_0
python-dateutil           2.8.1                      py_0    conda-forge
python-magic              0.4.18                   pypi_0    pypi
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
pywin32                   300              py37hcc03f2d_0    conda-forge
pywinpty                  0.5.7            py37hc8dfbb8_1    conda-forge
pyzmq                     22.0.1           py37h0d95fc2_0    conda-forge
qt                        5.12.9               h5909a2a_3    conda-forge
qtconsole                 5.0.2              pyhd8ed1ab_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
quetzal                   0.1                       dev_0    <develop>
r-assertthat              0.2.1             r36h6115d3f_2    conda-forge
r-backports               1.2.1             r36h6d2157b_0    conda-forge
r-base                    3.6.3                hddad469_6    conda-forge
r-base64enc               0.1_3           r36hda5aaf8_1004    conda-forge
r-cli                     2.3.0             r36hc72bb7e_0    conda-forge
r-cpp11                   0.2.6             r36hc72bb7e_0    conda-forge
r-crayon                  1.4.0             r36hc72bb7e_0    conda-forge
r-data.table              1.13.6            r36h6d2157b_0    conda-forge
r-digest                  0.6.27            r36h096a1c2_0    conda-forge
r-ellipsis                0.3.1             r36hda5aaf8_0    conda-forge
r-fansi                   0.4.2             r36h6d2157b_0    conda-forge
r-gdtools                 0.2.2             r36ha5114e6_1    conda-forge
r-glue                    1.4.2             r36h6d2157b_0    conda-forge
r-htmltools               0.5.1.1           r36ha856d6a_0    conda-forge
r-jsonlite                1.7.2             r36h6d2157b_0    conda-forge
r-juniperkernel           1.4.1.0         r36h796a38f_1005    conda-forge
r-lifecycle               0.2.0             r36h6115d3f_1    conda-forge
r-pbdzmq                  0.3_4             r36h5962c11_0    conda-forge
r-pillar                  1.4.7             r36hc72bb7e_0    conda-forge
r-rcpp                    1.0.6             r36ha856d6a_0    conda-forge
r-repr                    1.1.3             r36h785f33e_0    conda-forge
r-rlang                   0.4.10            r36h6d2157b_0    conda-forge
r-systemfonts             1.0.0             r36h93c4b31_0    conda-forge
r-utf8                    1.1.4           r36hda5aaf8_1003    conda-forge
r-vctrs                   0.3.6             r36h6d2157b_0    conda-forge
r-zeallot                 0.1.0           r36h6115d3f_1002    conda-forge
rasterio                  1.2.0            py37hc4b0cd6_0    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
scikit-learn              0.24.1                   pypi_0    pypi
scipy                     1.6.0                    pypi_0    pypi
selenium                  3.141.0                  pypi_0    pypi
send2trash                1.5.0                      py_0    conda-forge
setuptools                53.0.0                   pypi_0    pypi
shapely                   1.7.1                    pypi_0    pypi
simpervisor               0.4                pyhd8ed1ab_0    conda-forge
simpledbf                 0.2.6                    pypi_0    pypi
six                       1.15.0             pyh9f0ad1d_0    conda-forge
snowballstemmer           2.1.0                    pypi_0    pypi
snuggs                    1.4.7                      py_0    conda-forge
soupsieve                 2.1                      pypi_0    pypi
sphinx                    3.4.3                    pypi_0    pypi
sphinx-rtd-theme          0.5.1                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    1.0.3                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.4                    pypi_0    pypi
sqlite                    3.34.0               h8ffe710_0    conda-forge
terminado                 0.9.2            py37h03978a9_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
threadpoolctl             2.1.0                    pypi_0    pypi
tiledb                    2.1.6                hf84e3da_1    conda-forge
tk                        8.6.10               h8ffe710_1    conda-forge
tornado                   6.1              py37hcc03f2d_1    conda-forge
tqdm                      4.56.0                   pypi_0    pypi
traitlets                 5.0.5                      py_0    conda-forge
typing-extensions         3.7.4.3                       0    conda-forge
typing_extensions         3.7.4.3                    py_0    conda-forge
urllib3                   1.26.3             pyhd8ed1ab_0    conda-forge
utm                       0.7.0                    pypi_0    pypi
vc                        14.2                 hb210afc_2    conda-forge
vs2015_runtime            14.28.29325          h5e1d092_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                    pypi_0    pypi
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
widgetsnbextension        3.5.1            py37h03978a9_4    conda-forge
win_inet_pton             1.1.0            py37h03978a9_2    conda-forge
wincertstore              0.2             py37h03978a9_1006    conda-forge
winpty                    0.4.3                         4    conda-forge
xerces-c                  3.2.3                h0e60522_2    conda-forge
xlrd                      2.0.1                    pypi_0    pypi
xz                        5.2.5                h62dcd97_1    conda-forge
yarl                      1.6.3            py37hcc03f2d_1    conda-forge
zeromq                    4.3.3                h0e60522_3    conda-forge
zipp                      3.4.0                      py_0    conda-forge
zlib                      1.2.11            h62dcd97_1010    conda-forge
zope-interface            5.2.0                    pypi_0    pypi
zstd                      1.4.8                h4e2f164_1    conda-forge

**Comment by orlandoandradeb** [comment]
Sorry the comment is not really structured but with a single screen shot was not enough

**Comment by orlandoandradeb** [comment]
When I desintall  `rtree`  the importation of geopandas worked well. However, now I want to impot another library and it gives me an error related with `pyproj`  and when I start the installation with conda of pyproj it requires the rtree too.

**Comment by martinfleis** [comment]
You have installed pyproj using pip whilst gepandas using conda-forge. Pip installing packages with C dependencies (like pyproj) is known to cause trouble. Reinstalling pyproj using conda from conda-forge should resolve the issue.

```
pip uninstall pyproj
conda install -c conda-forge pyproj
```

**Comment by jonwangio** [comment]
This may be also due to version of the `rtree`, my workaround is to avoid the most up-to-date `rtree` and stick to the version earlier than 0.9.4 as: 

`conda install -c conda-forge rtree=0.9.3`

**Comment by m-y-reich** [comment]
Thank you so much @jonwangio, this solved it for me!

**Comment by alavenant** [comment]
Hy,

Install the 0.9.3 version of rtree doesn't solve the problem to me... If some one has an idea. Thanks.

My conda list result for rtree :
rtree                     0.9.3            py38hbf79ddb_0    conda-forge

**Comment by martinfleis** [comment]
@alavenant :

1) you can install `pygeos`, in which case geopandas uses STRtree in pygeos not rtree (and gives a significant performance gain at the same time).

2) if you have previously installed rtree via pip, try removing it first (`pip uninstall rtree`), there may be a conflict in links to `libspatialindex` C library.

**Comment by RichardScottOZ** [comment]
I had the same error with a new environment - the older rtree seemed to have solved for now.

**Comment by knaaptime** [comment]
we're also hitting this error on the [pysal segregation  CI](https://github.com/knaaptime/segregation/runs/2395382705?check_suite_focus=true). Interestingly, ive also got pygeos specified as a hard dependency in those environments, so not sure why rtree is being engaged at all

**Comment by jGaboardi** [comment]
> we're also hitting this error on the [pysal segregation CI](https://github.com/knaaptime/segregation/runs/2395382705?check_suite_focus=true). Interestingly, ive also got pygeos specified as a hard dependency in those environments, so not sure why rtree is being engaged at all

Also seeing this in [`spaghetti`](https://github.com/pysal/spaghetti/runs/2385962620?check_suite_focus=true#step:9:324), but seemingly only with Windows builds.

**Comment by martinfleis** [comment]
>  not sure why rtree is being engaged at all

@knaaptime GeoPandas tries to understand if it can or cannot load it here 
https://github.com/geopandas/geopandas/blob/f4a9763f90d65dea21e2e628e60326e27ca13576/geopandas/_compat.py#L201-L206

It seems that one solution for those relying on pygeos anyway would be to check for `OSError` alongside the current `ImportError`. That would disable rtree if it is incorrectly linked to libspatailindex.

**Comment by DR-azery** [comment]
just for info: downgrade to rtree 0.9.3 did solve the issue for me

**Comment by martinfleis** [comment]
I have reported it to rtree-feedstock (https://github.com/conda-forge/rtree-feedstock/issues/31). We can't solve it here.

**Comment by martinfleis** [comment]
This issue is caused by mixed channels in the environment. Make sure you use strict channel priority when installing from conda-forge. That should resolve the issue you may encounter under Windows. See more details in the [conda-forge docs](https://conda-forge.org/docs/user/tipsandtricks.html#using-multiple-channels). 

Specifying `-c conda-forge` in the installation command may not be enough if your channel priority is set to flexible. Also, note that mixing packages from PyPI and conda should be avoided if there's a conda-forge version.

To set channel priority to strict in a single environment:

```
conda config --env --add channels conda-forge
conda config --env --set channel_priority strict
```
I will close this now with this conclusion and we can reopen if it doesn't help. In any case, this is not an issue in geopandas code but with the installation of `rtree` package.

**Comment by henaogo** [comment]
I had the same issue and solved it updating Python. I was running Python 3.9.1 and update to 3.9.2 and solved.

For update Python with conda
`conda update python`

**Comment by baichuns** [comment]
I tried all the above solutions, none of them work for me, even down grade geopandas and rtree to the version mentioned above, I tried python 3.8 and 3.9, tried on very simple script, just import a few modules, but still not working. This really gives me a tough time. The error message is below, much appreciated if anyone has other ideas, I can try.  Thanks so much

  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "geopandas\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "geopandas\_config.py", line 126, in <module>
  File "geopandas\_config.py", line 112, in _default_use_pygeos
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "geopandas\_compat.py", line 149, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "rtree\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "rtree\index.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "rtree\core.py", line 128, in <module>
**OSError: could not find or load spatialindex_c-64.dll**
[76] Failed to execute script lineament_analysis

**Comment by jorisvandenbossche** [comment]
Note that the above issue report and solutions are not using PyInstaller, so your issue might be something different. 
(I don't have any experience myself with PyInstaller, so I can't provide any help)

**Comment by baichuns** [comment]
Oops, thanks

**Comment by msaifp** [comment]
> I tried all the above solutions, none of them work for me, even down grade geopandas and rtree to the version mentioned above, and modified the spec file, I tried on both python 3.8 and 3.9, and only use conda-forge channel. I used a very simple script for pyinstaller, just import a few modules, but still not working. This really gives me a tough time. The error message is below, much appreciated if anyone has other ideas, I can try. Thanks so much
> 
> File "", line 991, in _find_and_load
> File "", line 975, in _find_and_load_unlocked
> File "", line 671, in _load_unlocked File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module File "geopandas__init__.py", line 1, in
> File "", line 991, in _find_and_load
> File "", line 975, in _find_and_load_unlocked
> File "", line 671, in _load_unlocked
> File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
> File "geopandas_config.py", line 126, in
> File "geopandas_config.py", line 112, in _default_use_pygeos
> File "", line 991, in _find_and_load
> File "", line 975, in _find_and_load_unlocked
> File "", line 671, in _load_unlocked
> File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
> File "geopandas_compat.py", line 149, in
> File "", line 991, in _find_and_load
> File "", line 975, in _find_and_load_unlocked
> File "", line 671, in _load_unlocked File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module File "rtree__init__.py", line 1, in
> File "", line 991, in _find_and_load
> File "", line 975, in _find_and_load_unlocked
> File "", line 671, in _load_unlocked
> File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
> File "rtree\index.py", line 6, in
> File "", line 991, in _find_and_load
> File "", line 975, in _find_and_load_unlocked
> File "", line 671, in _load_unlocked
> File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
> File "rtree\core.py", line 128, in
> **OSError: could not find or load spatialindex_c-64.dll**
> [76] Failed to execute script lineament_analysis

I have the exact same error and have been trying for a couple of weeks to fix it based on solutions provided by others across the web but I still can't find a solution. Would be great to resolve this issue as I have a couple of projects I want to get done for my job soon.

**Comment by martinfleis** [comment]
None of the current geopandas maintainers has an experience with PyInstaller so we'll need help from someone who does. At the same time, this issue is not directly with GeoPandas but with `rtree` so you may want to try your luck there. There's not much we can do about it anyway.

**Comment by Khalilsqu** [comment]
I still keep getting the same error. Please resolve this issue. Thanks.

**Comment by mugumya21** [comment]
i have successfully solved this error , by running the following commands;
     OSError: could not find or load spatialindex_c-64.dll

		First run these 3 commands; in your environment
		install pygeos --channel conda-forge
		conda update python
		conda install scikit-learn-intelex

then refresh or restart the program, and you will smile.

**Comment by dingkai031** [comment]
I run into this problem, to fix this problem, I just create new environment and run
`conda create -n geopandas_env -c conda-forge geopandas`
https://github.com/conda-forge/geopandas-feedstock/issues/78#issuecomment-766724625

**Comment by alfurka** [comment]
> This may be also due to version of the `rtree`, my workaround is to avoid the most up-to-date `rtree` and stick to the version earlier than 0.9.4 as:
> 
> `conda install -c conda-forge rtree=0.9.3`

Somehow conda did not install it but pip worked for me:

> pip uninstall rtree
> pip install Rtree=0.9.3

Thanks!

**Comment by sunny3287358580** [comment]
> This may be also due to version of the `rtree`, my workaround is to avoid the most up-to-date `rtree` and stick to the version earlier than 0.9.4 as:
> 
> `conda install -c conda-forge rtree=0.9.3`

thank you
