### ISSUE TITLE
BUG: readthedocs is failing

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#2124]
RTD is failing (for some time already) - https://readthedocs.org/projects/geopandas/builds/14797073/

I'll try to fix that later tonight.

**Comment by martinfleis** [comment]
I am not able to reproduce the issue locally on mac or linux... I am going to allow doc builds for PRs and try to debug a bit. Might take a while.

**Comment by martinfleis** [comment]
It started failing after this commit. What is confusing is that it does not touch documentation. https://github.com/geopandas/geopandas/commit/632149a9ad2f85fab2d5a5237292cad95f08be17

**Comment by jorisvandenbossche** [comment]
One of the errors is geocoding failing. And that's something I actually also see if I run the snippet of the docs locally in my dev environment:

```
In [4]:     boros = geopandas.read_file(geopandas.datasets.get_path("nybb"))
   ...:     boros.BoroName
   ...:     boro_locations = geopandas.tools.geocode(boros.BoroName)
   ...:     boro_locations
---------------------------------------------------------------------------
gaierror                                  Traceback (most recent call last)
~/miniconda3/envs/geo/lib/python3.9/site-packages/urllib3/connection.py in _new_conn(self)
    168         try:
--> 169             conn = connection.create_connection(
    170                 (self._dns_host, self.port), self.timeout, **extra_kw

~/miniconda3/envs/geo/lib/python3.9/site-packages/urllib3/util/connection.py in create_connection(address, timeout, source_address, socket_options)
     72 
---> 73     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
     74         af, socktype, proto, canonname, sa = res

~/miniconda3/envs/geo/lib/python3.9/socket.py in getaddrinfo(host, port, family, type, proto, flags)
    953     addrlist = []
--> 954     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
    955         af, socktype, proto, canonname, sa = res

gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

NewConnectionError                        Traceback (most recent call last)
~/miniconda3/envs/geo/lib/python3.9/site-packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    698             # Make the request on the httplib connection object.
--> 699             httplib_response = self._make_request(
    700                 conn,

~/miniconda3/envs/geo/lib/python3.9/site-packages/urllib3/connectionpool.py in _make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    381         try:
--> 382             self._validate_conn(conn)
    383         except (SocketTimeout, BaseSSLError) as e:

~/miniconda3/envs/geo/lib/python3.9/site-packages/urllib3/connectionpool.py in _validate_conn(self, conn)
   1009         if not getattr(conn, "sock", None):  # AppEngine might not have  `.sock`
-> 1010             conn.connect()
   1011 

~/miniconda3/envs/geo/lib/python3.9/site-packages/urllib3/connection.py in connect(self)
    352         # Add certificate verification
--> 353         conn = self._new_conn()
    354         hostname = self.host

~/miniconda3/envs/geo/lib/python3.9/site-packages/urllib3/connection.py in _new_conn(self)
    180         except SocketError as e:
--> 181             raise NewConnectionError(
    182                 self, "Failed to establish a new connection: %s" % e

NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f1e16292460>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

MaxRetryError                             Traceback (most recent call last)
~/miniconda3/envs/geo/lib/python3.9/site-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    438             if not chunked:
--> 439                 resp = conn.urlopen(
    440                     method=request.method,

~/miniconda3/envs/geo/lib/python3.9/site-packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    782             )
--> 783             return self.urlopen(
    784                 method,

~/miniconda3/envs/geo/lib/python3.9/site-packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    782             )
--> 783             return self.urlopen(
    784                 method,

~/miniconda3/envs/geo/lib/python3.9/site-packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    754 
--> 755             retries = retries.increment(
    756                 method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]

~/miniconda3/envs/geo/lib/python3.9/site-packages/urllib3/util/retry.py in increment(self, method, url, response, error, _pool, _stacktrace)
    572         if new_retry.is_exhausted():
--> 573             raise MaxRetryError(_pool, url, error or ResponseError(cause))
    574 

MaxRetryError: HTTPSConnectionPool(host='photon.komoot.de', port=443): Max retries exceeded with url: /api?q=Staten+Island&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1e16292460>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

ConnectionError                           Traceback (most recent call last)
~/miniconda3/envs/geo/lib/python3.9/site-packages/geopy/adapters.py in _request(self, url, timeout, headers)
    386         try:
--> 387             resp = self.session.get(url, timeout=timeout, headers=headers)
    388         except Exception as error:

~/miniconda3/envs/geo/lib/python3.9/site-packages/requests/sessions.py in get(self, url, **kwargs)
    554         kwargs.setdefault('allow_redirects', True)
--> 555         return self.request('GET', url, **kwargs)
    556 

~/miniconda3/envs/geo/lib/python3.9/site-packages/requests/sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    541         send_kwargs.update(settings)
--> 542         resp = self.send(prep, **send_kwargs)
    543 

~/miniconda3/envs/geo/lib/python3.9/site-packages/requests/sessions.py in send(self, request, **kwargs)
    654         # Send the request
--> 655         r = adapter.send(request, **kwargs)
    656 

~/miniconda3/envs/geo/lib/python3.9/site-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    515 
--> 516             raise ConnectionError(e, request=request)
    517 

ConnectionError: HTTPSConnectionPool(host='photon.komoot.de', port=443): Max retries exceeded with url: /api?q=Staten+Island&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1e16292460>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

GeocoderUnavailable                       Traceback (most recent call last)
<ipython-input-4-9c44e2298cc7> in <module>
      1 boros = geopandas.read_file(geopandas.datasets.get_path("nybb"))
      2 boros.BoroName
----> 3 boro_locations = geopandas.tools.geocode(boros.BoroName)
      4 boro_locations

~/scipy/geopandas/geopandas/tools/geocoding.py in geocode(strings, provider, **kwargs)
     65     throttle_time = _get_throttle_time(provider)
     66 
---> 67     return _query(strings, True, provider, throttle_time, **kwargs)
     68 
     69 

~/scipy/geopandas/geopandas/tools/geocoding.py in _query(data, forward, provider, throttle_time, **kwargs)
    139         try:
    140             if forward:
--> 141                 results[i] = coder.geocode(s)
    142             else:
    143                 results[i] = coder.reverse((s.y, s.x), exactly_one=True)

~/miniconda3/envs/geo/lib/python3.9/site-packages/geopy/geocoders/photon.py in geocode(self, query, exactly_one, timeout, location_bias, language, limit, osm_tag)
    144         logger.debug("%s.geocode: %s", self.__class__.__name__, url)
    145         callback = partial(self._parse_json, exactly_one=exactly_one)
--> 146         return self._call_geocoder(url, callback, timeout=timeout)
    147 
    148     def reverse(

~/miniconda3/envs/geo/lib/python3.9/site-packages/geopy/geocoders/base.py in _call_geocoder(self, url, callback, timeout, is_json, headers)
    358         try:
    359             if is_json:
--> 360                 result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
    361             else:
    362                 result = self.adapter.get_text(url, timeout=timeout, headers=req_headers)

~/miniconda3/envs/geo/lib/python3.9/site-packages/geopy/adapters.py in get_json(self, url, timeout, headers)
    375 
    376     def get_json(self, url, *, timeout, headers):
--> 377         resp = self._request(url, timeout=timeout, headers=headers)
    378         try:
    379             return resp.json()

~/miniconda3/envs/geo/lib/python3.9/site-packages/geopy/adapters.py in _request(self, url, timeout, headers)
    397                     raise GeocoderServiceError(message)
    398                 else:
--> 399                     raise GeocoderUnavailable(message)
    400             elif isinstance(error, requests.Timeout):
    401                 raise GeocoderTimedOut("Service timed out")

GeocoderUnavailable: HTTPSConnectionPool(host='photon.komoot.de', port=443): Max retries exceeded with url: /api?q=Staten+Island&limit=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1e16292460>: Failed to establish a new connection: [Errno -2] Name or service not known'))

```

**Comment by martinfleis** [comment]
I see that as well but that does not stop sphinx from generating docs. I'll have a look into that as well but I don't think that is the issue.

**Comment by jorisvandenbossche** [comment]
Ah, yes. So it's the error related to nbsphinx that's the issue? From the build logs:

```
writing output... [ 80%] docs/reference/api/geopandas.sindex.RTreeIndex.query_bulk .. gallery/index

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/geopandas/conda/latest/lib/python3.9/site-packages/sphinx/events.py", line 101, in emit
    results.append(listener.handler(self.app, *args))
  File "/home/docs/checkouts/readthedocs.org/user_builds/geopandas/conda/latest/lib/python3.9/site-packages/nbsphinx.py", line 2085, in doctree_resolved
    filename = os.path.join(
  File "/home/docs/checkouts/readthedocs.org/user_builds/geopandas/conda/latest/lib/python3.9/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/home/docs/checkouts/readthedocs.org/user_builds/geopandas/conda/latest/lib/python3.9/genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'object'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/geopandas/conda/latest/lib/python3.9/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/geopandas/conda/latest/lib/python3.9/site-packages/sphinx/application.py", line 343, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/geopandas/conda/latest/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 293, in build_update
    self.build(to_build,
  File "/home/docs/checkouts/readthedocs.org/user_builds/geopandas/conda/latest/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 357, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/docs/checkouts/readthedocs.org/user_builds/geopandas/conda/latest/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 528, in write
    self._write_parallel(sorted(docnames),
  File "/home/docs/checkouts/readthedocs.org/user_builds/geopandas/conda/latest/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 565, in _write_parallel
    doctree = self.env.get_and_resolve_doctree(docname, self)
  File "/home/docs/checkouts/readthedocs.org/user_builds/geopandas/conda/latest/lib/python3.9/site-packages/sphinx/environment/__init__.py", line 532, in get_and_resolve_doctree
    self.apply_post_transforms(doctree, docname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/geopandas/conda/latest/lib/python3.9/site-packages/sphinx/environment/__init__.py", line 583, in apply_post_transforms
    self.events.emit('doctree-resolved', doctree, docname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/geopandas/conda/latest/lib/python3.9/site-packages/sphinx/events.py", line 109, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <function doctree_resolved at 0x7f1d880851f0> for event 'doctree-resolved' threw an exception (exception: join() argument must be str, bytes, or os.PathLike object, not 'object')

Extension error (nbsphinx):
Handler <function doctree_resolved at 0x7f1d880851f0> for event 'doctree-resolved' threw an exception (exception: join() argument must be str, bytes, or os.PathLike object, not 'object')
```

**Comment by martinfleis** [comment]
Yes. That is the one I am not able to reproduce locally.

Geocoding issue is resolved in geopy 2.2.0, we just need to change the pin.

**Comment by jorisvandenbossche** [comment]
So I can actually reproduce that build error with recreating the conda environment as done by readthedocs.

**Comment by martinfleis** [comment]
Using
```
conda env create --quiet --name 2125 --file doc/environment.yml
```
? 

Btw, the current build ends on this...
```
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... Killed


Command killed due to excessive memory consumption
```

**Comment by jorisvandenbossche** [comment]
Yes, but only with mamba instead of conda :)

**Comment by jorisvandenbossche** [comment]
One of the few packages we _don't_ pin in this environment is actually sphinx ..

https://github.com/geopandas/geopandas/blob/32e7cf35f07d38d0900664bef3604bbe27b18971/doc/environment.yml#L14

(probably one of the packages for which it makes most sense to pin :-))

Downgrading from sphinx 4.2.0 (which is what got installed) to sphinx 4.1.2 doesn't fix it though. Further downgrading to sphinx 4.0.3 doesn't give that error, but gives another .. 

```
Sphinx parallel build error:
nbsphinx.NotebookError: RuntimeError in _build/doctrees/nbsphinx/_build/doctrees/nbsphinx/_build/doctrees/nbsphinx/gallery/polygon_plotting_with_folium.ipynb:
Kernel didn't respond in 60 seconds
```

**Comment by jorisvandenbossche** [comment]
Hmm, so downgrading sphinx actually didn't help. After setting nbsphinx to not execute the notebook (to avoid the above error), I again get the original error ..

**Comment by martinfleis** [comment]
Can you try to figure out which notebook causes the failure if any?

**Comment by jorisvandenbossche** [comment]
I turned of the parallel building to get a more understandable verbose output, but then the build actually passes ..

**Comment by jorisvandenbossche** [comment]
But it seems to be for `gallery/index`

**Comment by martinfleis** [comment]
I think I have found the issue. Our change in #1737 broke `geoplot`. And that example, in some environments, probably kills the nbshinx. I was able to reproduce the issue locally now (not sure why).

Removing `nbshpinx-thumbnail` tag from the broken cell fixes the issue.

```py
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/opt/miniconda3/envs/geopandas_docs/lib/python3.9/site-packages/geoplot/geoplot.py in <module>
     22 try:
---> 23     from geopandas.plotting import _mapclassify_choro
     24 except ImportError:

ImportError: cannot import name '_mapclassify_choro' from 'geopandas.plotting' (/Users/martin/Git/geopandas/geopandas/plotting.py)

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-1-d8af561bf88a> in <module>
      1 import geopandas
----> 2 import geoplot
      3
      4 world = geopandas.read_file(
      5     geopandas.datasets.get_path('naturalearth_lowres')

/opt/miniconda3/envs/geopandas_docs/lib/python3.9/site-packages/geoplot/__init__.py in <module>
----> 1 from .geoplot import (
      2     pointplot, polyplot, choropleth, cartogram, kdeplot, sankey, voronoi, quadtree, webmap,
      3     __version__
      4 )
      5 from .crs import (

/opt/miniconda3/envs/geopandas_docs/lib/python3.9/site-packages/geoplot/geoplot.py in <module>
     23     from geopandas.plotting import _mapclassify_choro
     24 except ImportError:
---> 25     from geopandas.plotting import __pysal_choro as _mapclassify_choro
     26
     27 __version__ = "0.4.1"

ImportError: cannot import name '__pysal_choro' from 'geopandas.plotting' (/Users/martin/Git/geopandas/geopandas/plotting.py)
```

**Comment by jorisvandenbossche** [comment]
So it seems to have to do with the `nbgallery` directive. If I remove that, there is no error (but of course also no gallery overview page. The individual notebooks are still built though)

**Comment by jorisvandenbossche** [comment]
Ah, the fact that I removed nbgallery might have avoided needing the thumbnail, so also masking the issue
