### ISSUE TITLE
Writing GPKG file failing on Windows / Python 2.7

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/geopandas#974]
From https://github.com/geopandas/geopandas/pull/870#issuecomment-484003547

Currently, the tests for GPKG writing on Appveyor + Python 2.7 are skipped. 
The error we see is (https://ci.appveyor.com/project/jorisvandenbossche/geopandas-us6w0/builds/23408016/job/v7g468n7dml8t43v):

```
____ TestGeoDataFrameToFile.test_geodataframe_to_file[geodataframe0-GPKG] _____
self = <geopandas.tests.test_geodataframe_to_file.TestGeoDataFrameToFile instance at 0x000000000E29C288>
geodataframe =    a                              geometry
0  1  POINT (-73.55378500000001 45.508722)
1  2           POINT (-73.554138 45.50908)
ogr_driver = 'GPKG'
    def test_geodataframe_to_file(self, geodataframe, ogr_driver):
        expected_error = _expected_error_on(geodataframe, ogr_driver, _FIONA18)
        if expected_error:
            with pytest.raises(expected_error.type, match=expected_error.match):
                geodataframe.to_file(self.output_file, driver=ogr_driver)
        else:
>           self._assert_to_file_succeeds(geodataframe, ogr_driver)
geopandas\tests\test_geodataframe_to_file.py:327: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
geopandas\tests\test_geodataframe_to_file.py:330: in _assert_to_file_succeeds
    gdf.to_file(self.output_file, driver=ogr_driver)
geopandas\geodataframe.py:429: in to_file
    to_file(self, filename, driver, schema, **kwargs)
geopandas\io\file.py:123: in to_file
    colxn.writerecords(df.iterfeatures())
C:\Miniconda-x64\envs\test-environment\lib\site-packages\fiona\collection.py:421: in __exit__
    self.close()
C:\Miniconda-x64\envs\test-environment\lib\site-packages\fiona\collection.py:403: in close
    self.flush()
C:\Miniconda-x64\envs\test-environment\lib\site-packages\fiona\collection.py:393: in flush
    self.session.sync(self)
fiona/ogrext.pyx:1085: in fiona.ogrext.WritingSession.sync
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
>   ???
E   CPLE_AppDefinedError: sqlite3_exec(CREATE VIRTUAL TABLE "rtree_output_file_geom" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree
fiona/_err.pyx:185: CPLE_AppDefinedError
------------------------------ Captured log call ------------------------------
collection.py              156 WARNING  CPLE_AppDefined in The '' extension is not allowed by the GPKG specification, which may cause compatibility problems
collection.py              156 WARNING  CPLE_NotSupported in dataset c:\users\appveyor\appdata\local\temp\1\tmpxzg1ww\output_file does not support layer creation option ENCODING
collection.py              393 ERROR    CPLE_AppDefined in sqlite3_exec(CREATE VIRTUAL TABLE "rtree_output_file_geom" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree
```

So it gives an error indicating that sqlite was not properly build with rtree enabled. However, this should be the case since https://github.com/conda-forge/sqlite-feedstock/pull/20

@ljwolf noted here https://github.com/geopandas/geopandas/pull/870#issuecomment-484003547 that there might be a mistake in the bld script.

@ocefpaf @snorfalorpagus should maybe also open an issue on the sqlite feedstock?

**Comment by theroggy** [comment]
Same using python 3.6 on windows...

**Comment by jorisvandenbossche** [comment]
@theroggy how did you install geopandas / fiona?

**Comment by theroggy** [comment]
> @theroggy how did you install geopandas / fiona?

@jorisvandenbossche I used the following commands:
`conda create --name orthoseg python=3.6
  conda activate orthoseg`
`conda install --channel conda-forge keras-gpu tensorflow-gpu rasterio geopandas scikit-image owslib spyder`
`pip install segmentation-models   # No conda package available`

**Comment by martinfleis** [comment]
@theroggy Can you show output of `conda list`? You might have mixed conda channels, if your channel priority is not set to strict.

**Comment by theroggy** [comment]
> @theroggy Can you show output of `conda list`? You might have mixed conda channels, if your channel priority is not set to strict.

```
# packages in environment at C:\Tools\anaconda3\envs\orthoseg2:
#
# Name                    Version                   Build  Channel
_tflow_select             2.1.0                       gpu  
absl-py                   0.7.1                    py36_0    conda-forge
affine                    2.2.2                      py_0    conda-forge
alabaster                 0.7.12                     py_0    conda-forge
asn1crypto                0.24.0                py36_1003    conda-forge
astor                     0.7.1                      py_0    conda-forge
astroid                   2.2.5                    py36_0    conda-forge
attrs                     19.1.0                     py_0    conda-forge
babel                     2.6.0                      py_1    conda-forge
backcall                  0.1.0                      py_0    conda-forge
blas                      1.0                         mkl  
bleach                    3.1.0                      py_0    conda-forge
boost-cpp                 1.68.0            h6a4c333_1000    conda-forge
bzip2                     1.0.6             hfa6e2cd_1002    conda-forge
ca-certificates           2019.3.9             hecc5488_0    conda-forge
certifi                   2019.3.9                 py36_0    conda-forge
cffi                      1.12.3           py36hb32ad35_0    conda-forge
chardet                   3.0.4                 py36_1003    conda-forge
click                     7.0                        py_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
cloudpickle               1.0.0                      py_0    conda-forge
colorama                  0.4.1                      py_0    conda-forge
cryptography              2.6.1            py36hb32ad35_0    conda-forge
cudatoolkit               10.0.130                      0  
cudnn                     7.3.1                cuda10.0_0  
curl                      7.64.1               h4496350_0    conda-forge
cycler                    0.10.0                     py_1    conda-forge
cytoolz                   0.9.0.1         py36hfa6e2cd_1001    conda-forge
dask-core                 1.2.2                      py_0    conda-forge
decorator                 4.4.0                      py_0    conda-forge
defusedxml                0.5.0                      py_1    conda-forge
descartes                 1.1.0                      py_3    conda-forge
docutils                  0.14                  py36_1001    conda-forge
entrypoints               0.3                   py36_1000    conda-forge
expat                     2.2.5             he025d50_1002    conda-forge
fiona                     1.8.6            py36hce0be61_3    conda-forge
freetype                  2.10.0               h5db478b_0    conda-forge
freexl                    1.0.5             hd288d7e_1002    conda-forge
gast                      0.2.2                      py_0    conda-forge
gdal                      2.4.1            py36hdf5ee75_0    conda-forge
geopandas                 0.5.0                      py_2    conda-forge
geos                      3.7.1             he025d50_1000    conda-forge
geotiff                   1.4.3             h8408f58_1000    conda-forge
gettext                   0.19.8.1          hb01d8f6_1002    conda-forge
glib                      2.58.3            hc0c2ac7_1001    conda-forge
grpcio                    1.16.1           py36h351948d_1  
h5py                      2.9.0           nompi_py36h3cb27cb_1102    conda-forge
hdf4                      4.2.13            hf8e6fe8_1002    conda-forge
hdf5                      1.10.4          nompi_hcc15c50_1106    conda-forge
icc_rt                    2019.0.0             h0cc432a_1  
icu                       58.1                     vc14_0    conda-forge
idna                      2.8                   py36_1000    conda-forge
imageio                   2.5.0                    py36_0    conda-forge
imagesize                 1.1.0                      py_0    conda-forge
intel-openmp              2019.3                      203  
ipykernel                 5.1.1            py36h39e3cac_0    conda-forge
ipython                   7.5.0            py36h39e3cac_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
isort                     4.3.20                   py36_0    conda-forge
jedi                      0.13.3                   py36_0    conda-forge
jinja2                    2.10.1                     py_0    conda-forge
jpeg                      9c                hfa6e2cd_1001    conda-forge
jsonschema                3.0.1                    py36_0    conda-forge
jupyter_client            5.2.4                      py_3    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
kealib                    1.4.10            heacb130_1003    conda-forge
keras-applications        1.0.7                      py_1    conda-forge
keras-base                2.2.4                    py36_0  
keras-gpu                 2.2.4                         0  
keras-preprocessing       1.0.9                      py_1    conda-forge
keyring                   19.0.2                   py36_0    conda-forge
kiwisolver                1.1.0            py36he980bc4_0    conda-forge
krb5                      1.16.3            hdd46e55_1001    conda-forge
lazy-object-proxy         1.4.1            py36hfa6e2cd_0    conda-forge
libblas                   3.8.0                    10_mkl    conda-forge
libcblas                  3.8.0                    10_mkl    conda-forge
libcurl                   7.64.1               h4496350_0    conda-forge
libffi                    3.2.1             h6538335_1006    conda-forge
libgdal                   2.4.1                he26aab1_0    conda-forge
libiconv                  1.15              hfa6e2cd_1005    conda-forge
libkml                    1.3.0             h4fd0f3b_1009    conda-forge
liblapack                 3.8.0                    10_mkl    conda-forge
libnetcdf                 4.6.2             h396784b_1001    conda-forge
libpng                    1.6.37               h7602738_0    conda-forge
libpq                     11.3                 hb0bdaea_0    conda-forge
libprotobuf               3.7.1                h1a1b453_0    conda-forge
libsodium                 1.0.16            h2fa13f4_1001    conda-forge
libspatialindex           1.8.5                he025d50_4    conda-forge
libspatialite             4.3.0a            h6a0152f_1026    conda-forge
libssh2                   1.8.2                h642c060_2    conda-forge
libtiff                   4.0.10            h36446d0_1001    conda-forge
libxml2                   2.9.9                h9ce36c8_0    conda-forge
libxslt                   1.1.32            heafd4d3_1002    conda-forge
lxml                      4.3.3            py36heafd4d3_0    conda-forge
m2w64-expat               2.1.1                         2  
m2w64-gcc-libgfortran     5.3.0                         6  
m2w64-gcc-libs            5.3.0                         7  
m2w64-gcc-libs-core       5.3.0                         7  
m2w64-gettext             0.19.7                        2  
m2w64-gmp                 6.1.0                         2  
m2w64-libiconv            1.14                          6  
m2w64-libwinpthread-git   5.0.0.4634.697f757               2  
m2w64-xz                  5.2.2                         2  
mapclassify               2.0.1                      py_0    conda-forge
markdown                  2.6.11                     py_0    conda-forge
markupsafe                1.1.1            py36hfa6e2cd_0    conda-forge
matplotlib                3.1.0                    py36_0    conda-forge
matplotlib-base           3.1.0            py36h3e3dc42_0    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
mistune                   0.8.4           py36hfa6e2cd_1000    conda-forge
mkl                       2019.3                      203  
msys2-conda-epoch         20160418                      1  
munch                     2.3.2                      py_0    conda-forge
nbconvert                 5.5.0                      py_0    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
networkx                  2.3                        py_0    conda-forge
numpy                     1.16.3           py36h873a0b8_0    conda-forge
numpydoc                  0.9.1                      py_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openjpeg                  2.3.1                ha922770_0    conda-forge
openssl                   1.1.1b               hfa6e2cd_2    conda-forge
owslib                    0.17.1                     py_0    conda-forge
packaging                 19.0                       py_0    conda-forge
pandas                    0.24.2           py36h6538335_0    conda-forge
pandoc                    2.7.2                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.4.0                      py_0    conda-forge
pcre                      8.41              h6538335_1003    conda-forge
pickleshare               0.7.5                 py36_1000    conda-forge
pillow                    6.0.0            py36h9a613e6_0    conda-forge
pip                       19.1.1                   py36_0  
poppler                   0.67.0               heddaa77_6    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                11.3                 h06f7779_0    conda-forge
proj4                     5.2.0             h6538335_1003    conda-forge
prompt_toolkit            2.0.9                      py_0    conda-forge
protobuf                  3.7.1            py36he025d50_0    conda-forge
psutil                    5.6.2            py36hfa6e2cd_0    conda-forge
pycodestyle               2.5.0                      py_0    conda-forge
pycparser                 2.19                     py36_1    conda-forge
pyflakes                  2.1.1                      py_0    conda-forge
pygments                  2.4.1                      py_0    conda-forge
pylint                    2.3.1                    py36_0    conda-forge
pyopenssl                 19.0.0                   py36_0    conda-forge
pyparsing                 2.4.0                      py_0    conda-forge
pyproj                    1.9.6           py36hfa6e2cd_1001    conda-forge
pyqt                      5.9.2            py36h6538335_0    conda-forge
pyreadline                2.1                   py36_1000    conda-forge
pyrsistent                0.15.2           py36hfa6e2cd_0    conda-forge
pysocks                   1.7.0                    py36_0    conda-forge
python                    3.6.8                h9f7ef89_7  
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2019.1                     py_0    conda-forge
pywavelets                1.0.3            py36h452e1ab_1    conda-forge
pywin32-ctypes            0.2.0                 py36_1000    conda-forge
pyyaml                    5.1              py36hfa6e2cd_0    conda-forge
pyzmq                     18.0.1           py36he7828b0_1    conda-forge
qt                        5.9.7                hc6833c9_1    conda-forge
qtawesome                 0.5.7              pyh8a2030e_0    conda-forge
qtconsole                 4.4.4                      py_0    conda-forge
qtpy                      1.7.1              pyhde82777_0    conda-forge
rasterio                  1.0.23           py36hbf02ebe_0    conda-forge
requests                  2.22.0                   py36_0    conda-forge
rope                      0.14.0                     py_0    conda-forge
rtree                     0.8.3           py36h21ff451_1002    conda-forge
scikit-image              0.15.0           py36h6538335_0    conda-forge
scipy                     1.2.1            py36h29ff71c_0  
setuptools                41.0.1                   py36_0  
shapely                   1.6.4           py36h8921fb9_1004    conda-forge
sip                       4.19.8          py36h6538335_1000    conda-forge
six                       1.12.0                py36_1000    conda-forge
snowballstemmer           1.2.1                      py_1    conda-forge
snuggs                    1.4.6                      py_0    conda-forge
sphinx                    2.0.1                      py_0    conda-forge
sphinxcontrib-applehelp   1.0.1                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.1                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.2                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.2                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.1                      py_0    conda-forge
spyder                    3.3.4                    py36_1    conda-forge
spyder-kernels            0.4.4                    py36_0    conda-forge
sqlite                    3.28.0               he774522_0  
tensorboard               1.13.1                   py36_0    conda-forge
tensorflow                1.13.1          gpu_py36h9006a92_0  
tensorflow-base           1.13.1          gpu_py36h871c8ca_0  
tensorflow-estimator      1.13.0           py36h39e3cac_0    conda-forge
tensorflow-gpu            1.13.1               h0d30ee6_0  
termcolor                 1.1.0                      py_2    conda-forge
testpath                  0.4.2                   py_1001    conda-forge
tk                        8.6.9             hfa6e2cd_1001    conda-forge
toolz                     0.9.0                      py_1    conda-forge
tornado                   6.0.2            py36hfa6e2cd_0    conda-forge
traitlets                 4.3.2                 py36_1000    conda-forge
typed-ast                 1.3.5            py36hfa6e2cd_0    conda-forge
urllib3                   1.24.3                   py36_0    conda-forge
vc                        14.1                 h0510ff6_4  
vs2015_runtime            14.15.26706          h3a45250_4  
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  0.15.4                     py_0    conda-forge
wheel                     0.33.4                   py36_0  
win_inet_pton             1.1.0                    py36_0    conda-forge
wincertstore              0.2              py36h7fe50ca_0  
wrapt                     1.11.1           py36hfa6e2cd_0    conda-forge
xerces-c                  3.2.2             h6538335_1001    conda-forge
xz                        5.2.4             h2fa13f4_1001    conda-forge
yaml                      0.1.7             hfa6e2cd_1001    conda-forge
zeromq                    4.3.1             he025d50_1000    conda-forge
zlib                      1.2.11            h2fa13f4_1004    conda-forge

```

**Comment by theroggy** [comment]
@martinfleis , as I noticed sqlite isn't coming from conda-forge in the listing above, I had a look at the "strict channel priority.
So I changed .condarc to contain this:
```
channel_priority: strict
channels:
  - conda-forge
  - defaults
```
However, then I got errors installing because some dependencies/packages couldn't be installed. I suppose  because eg. keras-gpu doesn't seem to be available in conda-forge. So I removed the channel_priority: strict, but kept conda-forge at the top of the "channels" section.

Now I was able to install, and in my listing sqlite now is coming from conda-forge, but it still didn't help, I'm getting the same error.

My new conda list:
```
# packages in environment at C:\Tools\anaconda3\envs\orthoseg3:
#
# Name                    Version                   Build  Channel
_tflow_select             2.1.0                       gpu  
absl-py                   0.7.1                    py36_0    conda-forge
affine                    2.2.2                      py_0    conda-forge
asn1crypto                0.24.0                py36_1003    conda-forge
astor                     0.7.1                      py_0    conda-forge
attrs                     19.1.0                     py_0    conda-forge
blas                      1.0                         mkl  
boost-cpp                 1.68.0            h6a4c333_1000    conda-forge
bzip2                     1.0.6             hfa6e2cd_1002    conda-forge
ca-certificates           2019.3.9             hecc5488_0    conda-forge
certifi                   2019.3.9                 py36_0    conda-forge
cffi                      1.12.3           py36hb32ad35_0    conda-forge
chardet                   3.0.4                 py36_1003    conda-forge
click                     7.0                        py_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
cloudpickle               1.0.0                      py_0    conda-forge
cryptography              2.6.1            py36hb32ad35_0    conda-forge
cudatoolkit               10.0.130                      0  
cudnn                     7.3.1                cuda10.0_0  
curl                      7.64.1               h4496350_0    conda-forge
cycler                    0.10.0                     py_1    conda-forge
cytoolz                   0.9.0.1         py36hfa6e2cd_1001    conda-forge
dask-core                 1.2.2                      py_0    conda-forge
decorator                 4.4.0                      py_0    conda-forge
descartes                 1.1.0                      py_3    conda-forge
expat                     2.2.5             he025d50_1002    conda-forge
fiona                     1.8.6            py36hce0be61_3    conda-forge
freetype                  2.10.0               h5db478b_0    conda-forge
freexl                    1.0.5             hd288d7e_1002    conda-forge
gast                      0.2.2                      py_0    conda-forge
gdal                      2.4.1            py36hdf5ee75_0    conda-forge
geopandas                 0.5.0                      py_2    conda-forge
geos                      3.7.1             he025d50_1000    conda-forge
geotiff                   1.4.3             h8408f58_1000    conda-forge
gettext                   0.19.8.1          hb01d8f6_1002    conda-forge
glib                      2.58.3            hc0c2ac7_1001    conda-forge
grpcio                    1.16.1           py36h351948d_1  
h5py                      2.9.0           nompi_py36h3cb27cb_1102    conda-forge
hdf4                      4.2.13            hf8e6fe8_1002    conda-forge
hdf5                      1.10.4          nompi_hcc15c50_1106    conda-forge
icc_rt                    2019.0.0             h0cc432a_1  
icu                       58.1                     vc14_0    conda-forge
idna                      2.8                   py36_1000    conda-forge
imageio                   2.5.0                    py36_0    conda-forge
intel-openmp              2019.3                      203  
jpeg                      9c                hfa6e2cd_1001    conda-forge
kealib                    1.4.10            heacb130_1003    conda-forge
keras-applications        1.0.7                      py_1    conda-forge
keras-base                2.2.4                    py36_0  
keras-gpu                 2.2.4                         0  
keras-preprocessing       1.0.9                      py_1    conda-forge
kiwisolver                1.1.0            py36he980bc4_0    conda-forge
krb5                      1.16.3            hdd46e55_1001    conda-forge
libblas                   3.8.0                    10_mkl    conda-forge
libcblas                  3.8.0                    10_mkl    conda-forge
libcurl                   7.64.1               h4496350_0    conda-forge
libffi                    3.2.1             h6538335_1006    conda-forge
libgdal                   2.4.1                he26aab1_0    conda-forge
libiconv                  1.15              hfa6e2cd_1005    conda-forge
libkml                    1.3.0             h4fd0f3b_1009    conda-forge
liblapack                 3.8.0                    10_mkl    conda-forge
libnetcdf                 4.6.2             h396784b_1001    conda-forge
libpng                    1.6.37               h7602738_0    conda-forge
libpq                     11.3                 hb0bdaea_0    conda-forge
libprotobuf               3.7.1                h1a1b453_0    conda-forge
libspatialindex           1.8.5                he025d50_4    conda-forge
libspatialite             4.3.0a            h6a0152f_1026    conda-forge
libssh2                   1.8.2                h642c060_2    conda-forge
libtiff                   4.0.10            h36446d0_1001    conda-forge
libxml2                   2.9.9                h9ce36c8_0    conda-forge
libxslt                   1.1.32            heafd4d3_1002    conda-forge
lxml                      4.3.3            py36heafd4d3_0    conda-forge
m2w64-expat               2.1.1                         2  
m2w64-gcc-libgfortran     5.3.0                         6  
m2w64-gcc-libs            5.3.0                         7  
m2w64-gcc-libs-core       5.3.0                         7  
m2w64-gettext             0.19.7                        2  
m2w64-gmp                 6.1.0                         2  
m2w64-libiconv            1.14                          6  
m2w64-libwinpthread-git   5.0.0.4634.697f757               2  
m2w64-xz                  5.2.2                         2  
mapclassify               2.0.1                      py_0    conda-forge
markdown                  2.6.11                     py_0    conda-forge
matplotlib                3.1.0                    py36_1    conda-forge
matplotlib-base           3.1.0            py36h2852a4a_1    conda-forge
mkl                       2019.3                      203  
msys2-conda-epoch         20160418                      1  
munch                     2.3.2                      py_0    conda-forge
networkx                  2.3                        py_0    conda-forge
numpy                     1.16.3           py36h873a0b8_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openjpeg                  2.3.1                ha922770_0    conda-forge
openssl                   1.1.1b               hfa6e2cd_2    conda-forge
owslib                    0.17.1                     py_0    conda-forge
pandas                    0.24.2           py36he350917_0    conda-forge
pcre                      8.41              h6538335_1003    conda-forge
pillow                    6.0.0            py36h9a613e6_0    conda-forge
pip                       19.1.1                   py36_0    conda-forge
poppler                   0.67.0               heddaa77_6    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                11.3                 h06f7779_0    conda-forge
proj4                     5.2.0             h6538335_1003    conda-forge
protobuf                  3.7.1            py36he025d50_0    conda-forge
pycparser                 2.19                     py36_1    conda-forge
pyopenssl                 19.0.0                   py36_0    conda-forge
pyparsing                 2.4.0                      py_0    conda-forge
pyproj                    1.9.6           py36hfa6e2cd_1002    conda-forge
pyqt                      5.9.2            py36h6538335_0    conda-forge
pyreadline                2.1                   py36_1000    conda-forge
pysocks                   1.7.0                    py36_0    conda-forge
python                    3.6.7             he025d50_1004    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2019.1                     py_0    conda-forge
pywavelets                1.0.3            py36h452e1ab_1    conda-forge
pyyaml                    5.1              py36hfa6e2cd_0    conda-forge
qt                        5.9.7                hc6833c9_1    conda-forge
rasterio                  1.0.23           py36hbf02ebe_0    conda-forge
requests                  2.22.0                   py36_0    conda-forge
rtree                     0.8.3           py36h21ff451_1002    conda-forge
scikit-image              0.15.0           py36h6538335_0    conda-forge
scipy                     1.2.1            py36h29ff71c_0  
setuptools                41.0.1                   py36_0    conda-forge
shapely                   1.6.4           py36h8921fb9_1004    conda-forge
sip                       4.19.8          py36h6538335_1000    conda-forge
six                       1.12.0                py36_1000    conda-forge
snuggs                    1.4.6                      py_0    conda-forge
sqlite                    3.28.0               hfa6e2cd_0    conda-forge
tensorboard               1.13.1                   py36_0    conda-forge
tensorflow                1.13.1          gpu_py36h9006a92_0  
tensorflow-base           1.13.1          gpu_py36h871c8ca_0  
tensorflow-estimator      1.13.0           py36h39e3cac_0    conda-forge
tensorflow-gpu            1.13.1               h0d30ee6_0  
termcolor                 1.1.0                      py_2    conda-forge
tk                        8.6.9             hfa6e2cd_1001    conda-forge
toolz                     0.9.0                      py_1    conda-forge
tornado                   6.0.2            py36hfa6e2cd_0    conda-forge
urllib3                   1.24.3                   py36_0    conda-forge
vc                        14.1                 h0510ff6_4  
vs2015_runtime            14.15.26706          h3a45250_4  
werkzeug                  0.15.4                     py_0    conda-forge
wheel                     0.33.4                   py36_0    conda-forge
win_inet_pton             1.1.0                    py36_0    conda-forge
wincertstore              0.2                   py36_1002    conda-forge
xerces-c                  3.2.2             h6538335_1001    conda-forge
xz                        5.2.4             h2fa13f4_1001    conda-forge
yaml                      0.1.7             hfa6e2cd_1001    conda-forge
zlib                      1.2.11            h2fa13f4_1004    conda-forge

```

**Comment by martinfleis** [comment]
@theroggy after lengthy trials with different envs, I have found what is causing the issue. If you have clean env with geopandas only, everything works. Once you install rasterio, it breaks. Why, I have no idea. During installation of rasterio, Conda does this downgrade, so I guess the issue will be somewhere in it:

    The following packages will be DOWNGRADED:
    
      gdal                                 2.4.1-py36hdf5ee75_3 --> 2.4.1-py36hdf5ee75_0
      geotiff                                  1.5.1-h8f84788_2 --> 1.4.3-h8408f58_1000
      libgdal                                  2.4.1-h7dc65ee_3 --> 2.4.1-he26aab1_0
      libspatialite                        4.3.0a-h221747d_1028 --> 4.3.0a-h6a0152f_1026
      proj4                                    6.1.0-hc2d0af5_2 --> 5.2.0-h6538335_1003
      pyproj                               2.1.3-py36h3f740ce_2 --> 1.9.6-py36hfa6e2cd_1002

It still seems to be windows-only issue.

**Comment by theroggy** [comment]
@martinfleis thank you for putting this effort into it. I did an install of gdal, which triggered installing the new version of gdal again (amongst others) and also a downgrade to the previous rasterio version... and now the rtree error is gone :-). 
So it seems there is an error in the dependencies of the newest version of rasterio?

Thanks a lot!

**Comment by FelixBuehler** [comment]
I have the same issue, even with a completely new Anaconda installation, after which I ran `conda install -c conda-forge geopandas`
Can anyone without this problem tell me, which version of geopandas, fiona, gdal, rtree and sqlite they are using?

This is my current list of installed packages, after following steps:
1. installing anaconda
2. adding conda-forge to channels
3. conda install -c conda-forge geopandas



I have the same issue, even with a completely new Anaconda installation, after which I ran `conda install -c conda-forge geopandas`
Can anyone without this problem tell me, which version of geopandas, fiona, gdal, rtree and sqlite they are using?

This is my current list of installed packages, after following steps:
1. installing anaconda
2. adding conda-forge to channels
3. conda install -c conda-forge geopandas

`# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0
alabaster                 0.7.12                   py37_0
anaconda                  2019.10                  py37_0
anaconda-client           1.7.2                    py37_0
anaconda-navigator        1.9.7                    py37_0
anaconda-project          0.8.3                      py_0
asn1crypto                1.0.1                    py37_0
astroid                   2.3.1                    py37_0
astropy                   3.2.1            py37he774522_0
atomicwrites              1.3.0                    py37_1
attrs                     19.2.0                     py_0
babel                     2.7.0                      py_0
backcall                  0.1.0                    py37_0
backports                 1.0                        py_2
backports.functools_lru_cache 1.5                        py_2
backports.os              0.1.1                    py37_0
backports.shutil_get_terminal_size 1.0.0                    py37_2
backports.tempfile        1.0                        py_1
backports.weakref         1.0.post1                  py_1
beautifulsoup4            4.8.0                    py37_0
bitarray                  1.0.1            py37he774522_0
bkcharts                  0.2                      py37_0
blas                      1.0                         mkl
bleach                    3.1.0                    py37_0
blosc                     1.16.3               h7bd577a_0
bokeh                     1.3.4                    py37_0
boost-cpp                 1.70.0               h6a4c333_2    conda-forge
boto                      2.49.0                   py37_0
bottleneck                1.2.1            py37h452e1ab_1
bzip2                     1.0.8                he774522_0
ca-certificates           2019.8.28                     0
certifi                   2019.9.11                py37_0
cffi                      1.12.3           py37h7a1dbc1_0
chardet                   3.0.4                 py37_1003
click                     7.0                      py37_0
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
cloudpickle               1.2.2                      py_0
clyent                    1.2.2                    py37_1
colorama                  0.4.1                    py37_0
comtypes                  1.1.7                    py37_0
conda                     4.7.12                   py37_0    conda-forge
conda-build               3.18.9                   py37_3
conda-env                 2.6.0                         1
conda-package-handling    1.6.0            py37h62dcd97_0
conda-verify              3.4.2                      py_1
console_shortcut          0.1.1                         3
contextlib2               0.6.0                      py_0
cryptography              2.7              py37h7a1dbc1_0
curl                      7.65.3               h2a8f88b_0
cycler                    0.10.0                   py37_0
cython                    0.29.13          py37ha925a31_0
cytoolz                   0.10.0           py37he774522_0
dask                      2.5.2                      py_0
dask-core                 2.5.2                      py_0
decorator                 4.4.0                    py37_1
defusedxml                0.6.0                      py_0
distributed               2.5.2                      py_0
docutils                  0.15.2                   py37_0
entrypoints               0.3                      py37_0
et_xmlfile                1.0.1                    py37_0
expat                     2.2.5             he025d50_1004    conda-forge
fastcache                 1.1.0            py37he774522_0
filelock                  3.0.12                     py_0
fiona                     1.8.4            py37h22081e2_0
flask                     1.1.1                      py_0
freetype                  2.9.1                ha9979f8_1
freexl                    1.0.5             hd288d7e_1002    conda-forge
fsspec                    0.5.2                      py_0
future                    0.17.1                   py37_0
gdal                      2.3.3            py37hdf43c64_0
geopandas                 0.6.1                      py_0    conda-forge
geos                      3.7.1                h33f27b4_0
get_terminal_size         1.0.0                h38e98db_0
gevent                    1.4.0            py37he774522_0
glob2                     0.7                        py_0
greenlet                  0.4.15           py37hfa6e2cd_0
h5py                      2.9.0            py37h5e291fa_0
hdf4                      4.2.13               h712560f_2
hdf5                      1.10.4               h7ebc959_0
heapdict                  1.0.1                      py_0
html5lib                  1.0.1                    py37_0
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha66f8fd_1
idna                      2.8                      py37_0
imageio                   2.6.0                    py37_0
imagesize                 1.1.0                    py37_0
importlib_metadata        0.23                     py37_0
intel-openmp              2019.4                      245
ipykernel                 5.1.2            py37h39e3cac_0
ipython                   7.8.0            py37h39e3cac_0
ipython_genutils          0.2.0                    py37_0
ipywidgets                7.5.1                      py_0
isort                     4.3.21                   py37_0
itsdangerous              1.1.0                    py37_0
jdcal                     1.4.1                      py_0
jedi                      0.15.1                   py37_0
jinja2                    2.10.3                     py_0
joblib                    0.13.2                   py37_0
jpeg                      9b                   hb83a4c4_2
json5                     0.8.5                      py_0
jsonschema                3.0.2                    py37_0
jupyter                   1.0.0                    py37_7
jupyter_client            5.3.3                    py37_1
jupyter_console           6.0.0                    py37_0
jupyter_core              4.5.0                      py_0
jupyterlab                1.1.4              pyhf63ae98_0
jupyterlab_server         1.0.6                      py_0
kealib                    1.4.10            heacb130_1003    conda-forge
keyring                   18.0.0                   py37_0
kiwisolver                1.1.0            py37ha925a31_0
krb5                      1.16.1               hc04afaa_7
lazy-object-proxy         1.4.2            py37he774522_0
libarchive                3.3.3                h0643e63_5
libcurl                   7.65.3               h2a8f88b_0
libgdal                   2.3.3                h10f50ba_0
libiconv                  1.15                 h1df5818_7
libkml                    1.3.0             h4ece8bf_1010    conda-forge
liblief                   0.9.0                ha925a31_2
libnetcdf                 4.6.1                h411e497_2
libpng                    1.6.37               h2a8f88b_0
libpq                     11.2                 h3235a2c_0
libsodium                 1.0.16               h9d3ae62_0
libspatialindex           1.8.5                he025d50_4    conda-forge
libspatialite             4.3.0a            h6a0152f_1026    conda-forge
libssh2                   1.8.2                h7a1dbc1_0
libtiff                   4.0.10               hb898794_2
libxml2                   2.9.9                h464c3ec_0
libxslt                   1.1.33               h579f668_0
llvmlite                  0.29.0           py37ha925a31_0
locket                    0.2.0                    py37_1
lxml                      4.4.1            py37h1350720_0
lz4-c                     1.8.1.2              h2fa13f4_0
lzo                       2.10                 h6df0209_2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markupsafe                1.1.1            py37he774522_0
matplotlib                3.1.1            py37hc8f65d3_0
mccabe                    0.6.1                    py37_1
menuinst                  1.4.16           py37he774522_0
mistune                   0.8.4            py37he774522_0
mkl                       2019.4                      245
mkl-service               2.3.0            py37hb782905_0
mkl_fft                   1.0.14           py37h14836fe_0
mkl_random                1.1.0            py37h675688f_0
mock                      3.0.5                    py37_0
more-itertools            7.2.0                    py37_0
mpmath                    1.1.0                    py37_0
msgpack-python            0.6.1            py37h74a9793_1
msys2-conda-epoch         20160418                      1
multipledispatch          0.6.0                    py37_0
munch                     2.3.2                      py_0    conda-forge
navigator-updater         0.2.1                    py37_0
nbconvert                 5.6.0                    py37_1
nbformat                  4.4.0                    py37_0
networkx                  2.3                        py_0
nltk                      3.4.5                    py37_0
nose                      1.3.7                    py37_2
notebook                  6.0.1                    py37_0
numba                     0.45.1           py37hf9181ef_0
numexpr                   2.7.0            py37hdce8814_0
numpy                     1.16.5           py37h19fb1c0_0
numpy-base                1.16.5           py37hc3f5095_0
numpydoc                  0.9.1                      py_0
olefile                   0.46                     py37_0
openpyxl                  3.0.0                      py_0
openssl                   1.1.1d               he774522_2
packaging                 19.2                       py_0
pandas                    0.25.1           py37ha925a31_0
pandoc                    2.2.3.2                       0
pandocfilters             1.4.2                    py37_1
parso                     0.5.1                      py_0
partd                     1.0.0                      py_0
path.py                   12.0.1                     py_0
pathlib2                  2.3.5                    py37_0
patsy                     0.5.1                    py37_0
pcre                      8.43                 h6538335_0    conda-forge
pep8                      1.7.1                    py37_0
pickleshare               0.7.5                    py37_0
pillow                    6.2.0            py37hdc69c19_0
pip                       19.2.3                   py37_0
pkginfo                   1.5.0.1                  py37_0
pluggy                    0.13.0                   py37_0
ply                       3.11                     py37_0
powershell_shortcut       0.0.1                         2
proj4                     5.2.0             h6538335_1006    conda-forge
prometheus_client         0.7.1                      py_0
prompt_toolkit            2.0.10                     py_0
psutil                    5.6.3            py37he774522_0
py                        1.8.0                    py37_0
py-lief                   0.9.0            py37ha925a31_2
pycodestyle               2.5.0                    py37_0
pycosat                   0.6.3            py37hfa6e2cd_0
pycparser                 2.19                     py37_0
pycrypto                  2.6.1            py37hfa6e2cd_9
pycurl                    7.43.0.3         py37h7a1dbc1_0
pyflakes                  2.1.1                    py37_0
pygments                  2.4.2                      py_0
pylint                    2.4.2                    py37_0
pyodbc                    4.0.27           py37ha925a31_0
pyopenssl                 19.0.0                   py37_0
pyparsing                 2.4.2                      py_0
pyproj                    1.9.6            py37h6782396_0
pyqt                      5.9.2            py37h6538335_2
pyreadline                2.1                      py37_1
pyrsistent                0.15.4           py37he774522_0
pysocks                   1.7.1                    py37_0
pytables                  3.5.2            py37h1da0976_1
pytest                    5.2.1                    py37_0
pytest-arraydiff          0.3              py37h39e3cac_0
pytest-astropy            0.5.0                    py37_0
pytest-doctestplus        0.4.0                      py_0
pytest-openfiles          0.4.0                      py_0
pytest-remotedata         0.3.2                    py37_0
python                    3.7.4                h5263a28_0
python-dateutil           2.8.0                    py37_0
python-libarchive-c       2.8                     py37_13
pytz                      2019.3                     py_0
pywavelets                1.0.3            py37h8c2d366_1
pywin32                   223              py37hfa6e2cd_1
pywinpty                  0.5.5                 py37_1000
pyyaml                    5.1.2            py37he774522_0
pyzmq                     18.1.0           py37ha925a31_0
qt                        5.9.7            vc14h73c81de_0
qtawesome                 0.6.0                      py_0
qtconsole                 4.5.5                      py_0
qtpy                      1.9.0                      py_0
requests                  2.22.0                   py37_0
rope                      0.14.0                     py_0
rtree                     0.8.3           py37h21ff451_1002    conda-forge
ruamel_yaml               0.15.46          py37hfa6e2cd_0
scikit-image              0.15.0           py37ha925a31_0
scikit-learn              0.21.3           py37h6288b17_0
scipy                     1.3.1            py37h29ff71c_0
seaborn                   0.9.0                    py37_0
send2trash                1.5.0                    py37_0
setuptools                41.4.0                   py37_0
shapely                   1.6.4           py37h7d20962_1005    conda-forge
simplegeneric             0.8.1                    py37_2
singledispatch            3.4.0.3                  py37_0
sip                       4.19.8           py37h6538335_0
six                       1.12.0                   py37_0
snappy                    1.1.7                h777316e_3
snowballstemmer           2.0.0                      py_0
sortedcollections         1.1.2                    py37_0
sortedcontainers          2.1.0                    py37_0
soupsieve                 1.9.3                    py37_0
sphinx                    2.2.0                      py_0
sphinxcontrib             1.0                      py37_1
sphinxcontrib-applehelp   1.0.1                      py_0
sphinxcontrib-devhelp     1.0.1                      py_0
sphinxcontrib-htmlhelp    1.0.2                      py_0
sphinxcontrib-jsmath      1.0.1                      py_0
sphinxcontrib-qthelp      1.0.2                      py_0
sphinxcontrib-serializinghtml 1.1.3                      py_0
sphinxcontrib-websupport  1.1.2                      py_0
spyder                    3.3.6                    py37_0
spyder-kernels            0.5.2                    py37_0
sqlalchemy                1.3.9            py37he774522_0
sqlite                    3.30.0               he774522_0
statsmodels               0.10.1           py37h8c2d366_0
sympy                     1.4                      py37_0
tbb                       2019.4               h74a9793_0
tblib                     1.4.0                      py_0
terminado                 0.8.2                    py37_0
testpath                  0.4.2                    py37_0
tk                        8.6.8                hfa6e2cd_0
toolz                     0.10.0                     py_0
tornado                   6.0.3            py37he774522_0
tqdm                      4.36.1                     py_0
traitlets                 4.3.3                    py37_0
unicodecsv                0.14.1                   py37_0
urllib3                   1.24.2                   py37_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_0
wcwidth                   0.1.7                    py37_0
webencodings              0.5.1                    py37_1
werkzeug                  0.16.0                     py_0
wheel                     0.33.6                   py37_0
widgetsnbextension        3.5.1                    py37_0
win_inet_pton             1.1.0                    py37_0
win_unicode_console       0.5                      py37_0
wincertstore              0.2                      py37_0
winpty                    0.4.3                         4
wrapt                     1.11.2           py37he774522_0
xerces-c                  3.2.2             h6538335_1004    conda-forge
xlrd                      1.2.0                    py37_0
xlsxwriter                1.2.1                      py_0
xlwings                   0.15.10                  py37_0
xlwt                      1.3.0                    py37_0
xz                        5.2.4                h2fa13f4_4
yaml                      0.1.7                hc54c509_2
zeromq                    4.3.1                h33f27b4_3
zict                      1.0.0                      py_0
zipp                      0.6.0                      py_0
zlib                      1.2.11               h62dcd97_3
zstd                      1.3.7                h508b16e_0`

**Comment by martinfleis** [comment]
@FelixBuehler You have mixed channels in your environment. Try installing packages strictly from conda-forge (http://geopandas.org/install.html#creating-a-new-environment), mixed channels notoriously cause dependency conflicts.

```
conda create -n geo_env
conda activate geo_env
conda config --env --add channels conda-forge
conda config --env --set channel_priority strict
conda install geopandas
```

**Comment by FelixBuehler** [comment]
It worked on my private computer tho. Gonna check it again tomorrow in my workplace, maybe I missed something somewhere.

**Comment by FelixBuehler** [comment]
Still the same error on the other computer. Did the exact same steps as before.
Any idea, what might be the problem?

**Comment by martinfleis** [comment]
@FelixBuehler is this behaviour related to Spyder or it does not matter?

**Comment by FelixBuehler** [comment]
Not sure, if those are the correct steps, but when i open Anaconda Prompt, type activate geo_env and then run "python be.py", the scripts works without error. So i would suggest it's a spyder problem?

**Comment by martinfleis** [comment]
I think it is. I am not using Spyder, so just a guess - error says that `table "rtree_2019-10_buergerschaftliches-engagement_4326_geom" already exists'`. Can you somehow clean Spyder environment? Or try different names for your objects? I am not sure if this is something we can fix on our side.

**Comment by FelixBuehler** [comment]
Actually the error message right now is this. I already uninstalled Anaconda and spyder several times and removed the folders which i could find in %user%.
What do you mean with different names for the objects? Variables? File Name?


```
Traceback (most recent call last):

  File "fiona/_err.pyx", line 201, in fiona._err.GDALErrCtxManager.__exit__

CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE "rtree_2019-10_buergerschaftliches-engagement_4326_geom" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'

be.py done.
Runtime: 0.2 seconds.
Exception ignored in: 'fiona._shim.gdal_flush_cache'
Traceback (most recent call last):
  File "fiona/_err.pyx", line 201, in fiona._err.GDALErrCtxManager.__exit__
fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE "rtree_2019-10_buergerschaftliches-engagement_4326_geom" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'
```

**Comment by martinfleis** [comment]
@FelixBuehler well, my previous idea does not apply to this error.

This is sqlite issue, not GeoPandas. And persistent one, as it was already fixed once (https://github.com/conda-forge/fiona-feedstock/issues/53, https://github.com/conda-forge/sqlite-feedstock/pull/20).

**Comment by FelixBuehler** [comment]
I don't know why, but today I also got the error without using spyder. I really have no idea why this is so unconsistent...

**Comment by anitagraser** [comment]
I also get this error after finally figuring out a channel order that creates an otherwise working geopandas installation on Windows.

**Comment by FelixBuehler** [comment]
I finally gave it up on windows. Im using it via Virtual Box in Linux. 
Not solving the problem tho, but now I don't get an error, but my python console crashes everytime I try to write a GPKG.

**Comment by theroggy** [comment]
For me (still on windows), I can write a gpkg but I still get an error that the rtree module is not available in sqlite. The gpkg created indeed does not have a spatial index, but when needit I add it in QGis.

**Comment by anitagraser** [comment]
I have one Win environment that runs without errors but it's a couple of months old:

```
# Name                    Version                   Build  Channel
affine                    2.2.2                      py_0    conda-forge
alabaster                 0.7.12                   pypi_0    pypi
altair                    3.2.0                    py37_0    conda-forge
anaconda-client           1.7.2                    py37_0
asn1crypto                0.24.0                py37_1003    conda-forge
atomicwrites              1.3.0                    py37_1
attrs                     19.1.0                     py_0    conda-forge
babel                     2.7.0                    pypi_0    pypi
backcall                  0.1.0                    py37_0
beautifulsoup4            4.8.0                    py37_0
blas                      1.0                         mkl
bleach                    3.1.0                    py37_0
bokeh                     1.3.4                    py37_0
boost-cpp                 1.68.0            h6a4c333_1000    conda-forge
boto3                     1.9.186                    py_0    conda-forge
botocore                  1.12.187                   py_0    conda-forge
branca                    0.3.1                      py_0    conda-forge
bzip2                     1.0.6             hfa6e2cd_1002    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
cartopy                   0.17.0          py37h814cdbc_1004    conda-forge
certifi                   2019.11.28               py37_0    conda-forge
cffi                      1.12.3           py37hb32ad35_0    conda-forge
cftime                    1.0.3.4         py37h8c2d366_1001
chardet                   3.0.4                 py37_1003    conda-forge
click                     7.0                        py_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
cloudpickle               1.2.2                      py_0
clyent                    1.2.2                    py37_1
colorama                  0.4.1                    py37_0
colorcet                  2.0.2                      py_0    pyviz
conda                     4.7.12                   py37_0    conda-forge
conda-build               3.18.9                   py37_3
conda-package-handling    1.3.11                   py37_0
contextily                1.0rc2                     py_0    conda-forge
cryptography              2.7              py37hb32ad35_0    conda-forge
curl                      7.65.1               h4496350_0    conda-forge
cycler                    0.10.0                     py_1    conda-forge
cytoolz                   0.10.0           py37he774522_0
dask                      2.6.0                      py_0
dask-core                 2.6.0                      py_0
datashader                0.8.0                      py_0    pyviz
datashape                 0.5.4                    py37_1
decorator                 4.4.0                    py37_1
defusedxml                0.6.0                      py_0
descartes                 1.1.0                      py_3
distributed               2.6.0                      py_0
docutils                  0.14                  py37_1001    conda-forge
entrypoints               0.3                      py37_0
expat                     2.2.5             habb2df7_1003    conda-forge
filelock                  3.0.12                     py_0
fiona                     1.8.4           py37h0d92105_1001    conda-forge
folium                    0.10.0                     py_0    conda-forge
freetype                  2.10.0               h5db478b_0    conda-forge
freexl                    1.0.5             hd288d7e_1002    conda-forge
fsspec                    0.5.2                      py_0
gdal                      2.3.3            py37hdf5ee75_1    conda-forge
geographiclib             1.49                       py_0    conda-forge
geopandas                 0.5.0                      py_3    conda-forge
geopy                     1.20.0                     py_0    conda-forge
geos                      3.7.1                h33f27b4_0
geotiff                   1.4.3             h8408f58_1000    conda-forge
geoviews                  1.6.5                      py_0    pyviz
geoviews-core             1.6.5                      py_0    pyviz
gettext                   0.19.8.1          hb01d8f6_1002    conda-forge
glib                      2.58.3            hc0c2ac7_1001    conda-forge
glob2                     0.7                        py_0
hdf4                      4.2.13            hf8e6fe8_1002    conda-forge
hdf5                      1.10.4          nompi_hcc15c50_1106    conda-forge
heapdict                  1.0.1                      py_0
holoviews                 1.12.6                     py_0
hvplot                    0.5.2                      py_0    pyviz
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.1                     vc14_0    conda-forge
idna                      2.8                   py37_1000    conda-forge
imageio                   2.6.1                    py37_0
imagesize                 1.1.0                    pypi_0    pypi
importlib_metadata        0.17                     py37_1
intel-openmp              2019.4                      245
ipykernel                 5.1.1            py37h39e3cac_0
ipython                   7.6.1            py37h39e3cac_0
ipython_genutils          0.2.0                    py37_0
ipywidgets                7.5.1                      py_0
jedi                      0.13.3                   py37_0
jinja2                    2.10.1                   py37_0
jmespath                  0.9.4                      py_0    conda-forge
joblib                    0.13.2                     py_0    conda-forge
jpeg                      9c                hfa6e2cd_1001    conda-forge
json5                     0.8.5                      py_0
jsonschema                3.0.1                    py37_0
jupyter                   1.0.0                    py37_7
jupyter_client            5.2.4                    py37_0
jupyter_console           6.0.0                    py37_0
jupyter_core              4.5.0                      py_0
jupyterlab                1.1.4              pyhf63ae98_0
jupyterlab_server         1.0.6                      py_0
kealib                    1.4.10            heacb130_1003    conda-forge
kiwisolver                1.1.0            py37he980bc4_0    conda-forge
krb5                      1.16.3            hdd46e55_1001    conda-forge
libarchive                3.3.3                h0643e63_5
libblas                   3.8.0                     8_mkl    conda-forge
libcblas                  3.8.0                     8_mkl    conda-forge
libcurl                   7.65.1               h4496350_0    conda-forge
libffi                    3.2.1             h6538335_1006    conda-forge
libgdal                   2.3.3                he26aab1_1    conda-forge
libiconv                  1.15              hfa6e2cd_1005    conda-forge
libkml                    1.3.0             h4fd0f3b_1009    conda-forge
liblapack                 3.8.0                     8_mkl    conda-forge
liblief                   0.9.0                ha925a31_2
libnetcdf                 4.6.2             h396784b_1001    conda-forge
libpng                    1.6.37               h7602738_0    conda-forge
libpq                     11.4                 hb0bdaea_1    conda-forge
libsodium                 1.0.16               h9d3ae62_0
libspatialindex           1.8.5                he025d50_4    conda-forge
libspatialite             4.3.0a            h6a0152f_1026    conda-forge
libssh2                   1.8.2                h642c060_2    conda-forge
libtiff                   4.0.10               hb898794_2
libxml2                   2.9.9                h9ce36c8_1    conda-forge
llvmlite                  0.30.0           py37ha925a31_0
locket                    0.2.0                    py37_1
lz4-c                     1.8.3             he025d50_1001    conda-forge
lzo                       2.10                 h6df0209_2
m2w64-expat               2.1.1                         2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gettext             0.19.7                        2
m2w64-gmp                 6.1.0                         2
m2w64-libiconv            1.14                          6
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
m2w64-xz                  5.2.2                         2
markupsafe                1.1.1            py37he774522_0
matplotlib                3.1.1                    py37_0    conda-forge
matplotlib-base           3.1.1            py37h2852a4a_0    conda-forge
menuinst                  1.4.16           py37he774522_0
mercantile                1.1.1                      py_0    conda-forge
mistune                   0.8.4            py37he774522_0
mkl                       2019.4                      245
more-itertools            7.2.0                    py37_0
msgpack-python            0.6.1            py37h74a9793_1
msys2-conda-epoch         20160418                      1
multipledispatch          0.6.0                    py37_0
munch                     2.3.2                      py_0    conda-forge
nbconvert                 5.5.0                      py_0
nbformat                  4.4.0                    py37_0
netcdf4                   1.4.2            py37h812ae01_0
networkx                  2.4                        py_0
notebook                  5.7.8                    py37_0
numba                     0.46.0           py37hf9181ef_0
numpy                     1.16.4           py37hc71023c_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openjpeg                  2.3.1                ha922770_0    conda-forge
openssl                   1.1.1d               hfa6e2cd_0    conda-forge
owslib                    0.18.0                     py_0    conda-forge
packaging                 19.0                     py37_0
pandas                    0.24.2           py37he350917_0    conda-forge
pandoc                    2.2.3.2                       0
pandocfilters             1.4.2                    py37_1
param                     1.9.2                      py_0
parso                     0.5.0                      py_0
partd                     1.0.0                      py_0
patch                     2.5.9                         1    https://repo.anaconda.com/pkgs/free
patsy                     0.5.1                      py_0    conda-forge
pcre                      8.41              h6538335_1003    conda-forge
pickleshare               0.7.5                    py37_0
pillow                    6.1.0            py37h9a613e6_0    conda-forge
pip                       19.1.1                   py37_0    conda-forge
pkginfo                   1.5.0.1                  py37_0
pluggy                    0.12.0                     py_0
poppler                   0.67.0               heddaa77_6    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                11.4                 h06f7779_1    conda-forge
proj4                     5.2.0             h6538335_1006    conda-forge
prometheus_client         0.7.1                      py_0
prompt_toolkit            2.0.9                    py37_0
psutil                    5.6.3            py37he774522_0
py                        1.8.0                    py37_0
py-lief                   0.9.0            py37ha925a31_2
pycosat                   0.6.3            py37hfa6e2cd_0
pycparser                 2.19                     py37_1    conda-forge
pyct                      0.4.6                      py_0    pyviz
pyct-core                 0.4.6                      py_0    pyviz
pyepsg                    0.4.0                      py_0    conda-forge
pygments                  2.4.2                      py_0
pykdtree                  1.3.1           py37h452e1ab_1002    conda-forge
pyopenssl                 19.0.0                   py37_0    conda-forge
pyparsing                 2.4.0                      py_0    conda-forge
pyproj                    1.9.6           py37hfa6e2cd_1002    conda-forge
pyqt                      5.9.2            py37h6538335_0    conda-forge
pyrsistent                0.14.11          py37he774522_0
pyshp                     2.1.0                      py_0    conda-forge
pysocks                   1.7.0                    py37_0    conda-forge
pytest                    5.0.1                    py37_0
python                    3.7.3                h510b542_1    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
python-libarchive-c       2.8                     py37_13
pytz                      2019.1                     py_0    conda-forge
pyviz_comms               0.7.2                      py_0
pywavelets                1.1.1            py37he774522_0
pywin32                   223              py37hfa6e2cd_1
pywinpty                  0.5.5                 py37_1000
pyyaml                    5.1.2            py37he774522_0
pyzmq                     18.0.0           py37ha925a31_0
qt                        5.9.7                hc6833c9_1    conda-forge
qtconsole                 4.5.5                      py_0
rasterio                  1.0.13           py37h299afd1_0    conda-forge
requests                  2.22.0                   py37_0    conda-forge
rtree                     0.8.3           py37h21ff451_1002    conda-forge
ruamel_yaml               0.15.46          py37hfa6e2cd_0
s3transfer                0.2.1                    py37_0    conda-forge
scikit-image              0.15.0           py37ha925a31_0
scikit-learn              0.22.1           py37h7208079_1    conda-forge
scipy                     1.2.1            py37h29ff71c_0
seaborn                   0.9.0                      py_1    conda-forge
send2trash                1.5.0                    py37_0
setuptools                41.0.1                   py37_0    conda-forge
shapely                   1.6.4           py37h7d20962_1005    conda-forge
sip                       4.19.8          py37h6538335_1000    conda-forge
six                       1.12.0                py37_1000    conda-forge
snowballstemmer           2.0.0                    pypi_0    pypi
snuggs                    1.4.6                      py_0    conda-forge
sortedcontainers          2.1.0                    py37_0
soupsieve                 1.9.2                    py37_0
sphinx                    2.2.1                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.1                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.1                    pypi_0    pypi
sphinxcontrib-htmlhelp    1.0.2                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.2                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.3                    pypi_0    pypi
sqlite                    3.29.0               hfa6e2cd_0    conda-forge
statsmodels               0.10.0           py37hfa6e2cd_0    conda-forge
tbb                       2019.4               h74a9793_0
tblib                     1.4.0                      py_0
terminado                 0.8.2                    py37_0
testpath                  0.4.2                    py37_0
tk                        8.6.9             hfa6e2cd_1002    conda-forge
toolz                     0.10.0                     py_0
tornado                   6.0.3            py37hfa6e2cd_0    conda-forge
tqdm                      4.32.1                     py_0
traitlets                 4.3.2                    py37_0
urllib3                   1.24.3                   py37_0    conda-forge
vc                        14.1                 h0510ff6_4
vincent                   0.4.4                      py_1    conda-forge
vs2015_runtime            14.16.27012          hf0eaf9b_0
wcwidth                   0.1.7                    py37_0
webencodings              0.5.1                    py37_1
wheel                     0.33.4                   py37_0    conda-forge
widgetsnbextension        3.5.1                    py37_0
win_inet_pton             1.1.0                    py37_0    conda-forge
wincertstore              0.2                   py37_1002    conda-forge
winpty                    0.4.3                         4
xarray                    0.13.0                     py_0
xerces-c                  3.2.2             hb1a71c1_1002    conda-forge
xz                        5.2.4             h2fa13f4_1001    conda-forge
yaml                      0.1.7                hc54c509_2
zeromq                    4.3.1                h33f27b4_3
zict                      1.0.0                      py_0
zipp                      0.5.2                      py_0
zlib                      1.2.11            h2fa13f4_1004    conda-forge
zstd                      1.3.7                h508b16e_0
```
